### ISSUE TITLE
When a page pops, a dialog or bottomsheet cannot be closed automatically

### ISSUE THREAD

**Issue by bitores** [emanuel-braz/one_context#7]
![Untitled](https://user-images.githubusercontent.com/17512181/101570861-3781ae00-3a12-11eb-964f-46c921506a70.gif)

**Comment by emanuel-braz** [comment]
Hi @bitores 
If you need to close dialogBoxes you just need to call `OneContext().popDialog()`
If you need close dialogs when android button is pressed, please await for the next release, this feature will be delivered soon.

The dialogBoxes in this package is not intended to be closed automatically when a route pops(Android back pressed), the behavior expected is to close the dialogs(if visible) first and after that, close the page.

I hope I managed to answer you, if not, please, leave a comment. I would appreciate sugestions too.

**Comment by emanuel-braz** [comment]
Hi @bitores, please, can you check this branch if it works for your needs?

Configure the one_context package's dependency to the github in `pubspec.yaml` 
```yaml
  one_context:
    git:
      url: git://github.com/emanuel-braz/one_context.git
      ref: feature/android-backbutton
```
